Add Java for some tricky Blu-ray discs

diff --git a/makemkv/Dockerfile b/makemkv/Dockerfile
--- a/makemkv/Dockerfile
+++ b/makemkv/Dockerfile
@@ -1,12 +1,25 @@
 FROM debian:stretch-slim
 
+# This disc requires Java runtime (JRE), but none was found. Certain functions will fail, please install Java. See http://www.makemkv.com/bdjava/ for details.
+RUN set -eux; \
+# update-alternatives: error: error creating symbolic link '/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory
+	mkdir -p /usr/share/man/man1; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		openjdk-8-jre-headless \
+	; \
+	rm -rf /var/lib/apt/lists/*
+
 # http://www.makemkv.com/forum2/viewtopic.php?f=3&t=224
 ENV MAKEMKV_VERSION 1.12.0
 
 # beta code: http://www.makemkv.com/forum2/viewtopic.php?f=5&t=1053
 RUN set -ex; \
 	\
-	buildDeps=' \
+	savedAptMark="$(apt-mark showmanual)"; \
+	\
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
 		ca-certificates \
 		g++ \
 		gcc \
@@ -18,9 +31,7 @@ RUN set -ex; \
 		pkg-config \
 		wget \
 		zlib1g-dev \
-	'; \
-	apt-get update; \
-	apt-get install -y --no-install-recommends $buildDeps; \
+	; \
 	rm -rf /var/lib/apt/lists/*; \
 	\
 	export PREFIX='/usr/local'; \
@@ -44,12 +55,16 @@ RUN set -ex; \
 		rm -r "$ball"; \
 	done; \
 	\
-	apt-mark manual \
-		libavcodec57 \
-		libqtdbus4 \
-		libqtgui4 \
-		libssl1.1 \
+	apt-mark auto '.*' > /dev/null; \
+	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
+	find /usr/local -type f -executable -exec ldd '{}' ';' \
+		| awk '/=>/ { print $(NF-1) }' \
+		| sort -u \
+		| xargs -r dpkg-query --search \
+		| cut -d: -f1 \
+		| sort -u \
+		| xargs -r apt-mark manual \
 	; \
-	apt-get purge -y --auto-remove $buildDeps
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false
 
 CMD ["makemkv"]
