Resync docker-master with docker-library/docker, fix build

diff --git a/docker-master/dind/Dockerfile b/docker-master/dind/Dockerfile
--- a/docker-master/dind/Dockerfile
+++ b/docker-master/dind/Dockerfile
@@ -1,13 +1,23 @@
 FROM tianon/docker-master
 
 # https://github.com/docker/docker/blob/master/project/PACKAGERS.md#runtime-dependencies
-RUN apk add --no-cache \
+RUN set -eux; \
+	apk add --no-cache \
 		btrfs-progs \
 		e2fsprogs \
 		e2fsprogs-extra \
 		iptables \
 		xfsprogs \
-		xz
+		xz \
+# pigz: https://github.com/moby/moby/pull/35697 (faster gzip implementation)
+		pigz \
+	; \
+# only install zfs if it's available for the current architecture
+# https://git.alpinelinux.org/cgit/aports/tree/main/zfs/APKBUILD?h=3.6-stable#n9 ("all !armhf !ppc64le" as of 2017-11-01)
+# "apk info XYZ" exits with a zero exit code but no output when the package exists but not for this arch
+	if zfs="$(apk info --no-cache --quiet zfs)" && [ -n "$zfs" ]; then \
+		apk add --no-cache zfs; \
+	fi
 
 # TODO aufs-tools
 
@@ -18,11 +28,12 @@ RUN set -x \
 	&& echo 'dockremap:165536:65536' >> /etc/subuid \
 	&& echo 'dockremap:165536:65536' >> /etc/subgid
 
-ENV DIND_COMMIT 3b5fac462d21ca164b3778647420016315289034
+# https://github.com/docker/docker/tree/master/hack/dind
+ENV DIND_COMMIT 52379fa76dee07ca038624d639d9e14f4fb719ff
 
 RUN set -ex; \
-	apk add --no-cache --virtual .fetch-deps libressl; \
-	wget -O /usr/local/bin/dind "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind"; \
+	apk add --no-cache --virtual .fetch-deps curl; \
+	curl -fL -o /usr/local/bin/dind "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind"; \
 	chmod +x /usr/local/bin/dind; \
 	apk del .fetch-deps
 
