Update prometheus and node_exporter

diff --git a/prometheus/node-exporter/Dockerfile b/prometheus/node-exporter/Dockerfile
--- a/prometheus/node-exporter/Dockerfile
+++ b/prometheus/node-exporter/Dockerfile
@@ -1,9 +1,9 @@
-FROM alpine:3.6
+FROM alpine:3.8
 
 WORKDIR /opt/node-exporter
 ENV PATH /opt/node-exporter:$PATH
 
-ENV NODE_EXPORTER_VERSION 0.12.0
+ENV NODE_EXPORTER_VERSION 0.16.0
 
 RUN set -ex; \
 	\
@@ -12,7 +12,16 @@ RUN set -ex; \
 		libressl \
 	; \
 	\
-	wget -O /tmp/node-exporter.tar.gz "https://github.com/prometheus/node_exporter/releases/download/${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.linux-amd64.tar.gz"; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		aarch64) promArch='arm64'   ;; \
+		armhf)   promArch='armv6'   ;; \
+		x86)     promArch='386'     ;; \
+		x86_64)  promArch='amd64'   ;; \
+		*) echo >&2 "error: unsupported arch: $apkArch"; exit 1 ;; \
+	esac; \
+	\
+	wget -O /tmp/node-exporter.tar.gz "https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.linux-$promArch.tar.gz"; \
 	tar \
 		--extract \
 		--file /tmp/node-exporter.tar.gz \
@@ -21,7 +30,7 @@ RUN set -ex; \
 	; \
 	rm /tmp/node-exporter.tar.gz; \
 	\
-	node_exporter -version; \
+	node_exporter --version; \
 	\
 	apk del .fetch-deps
 
