Implement better "versions" library
This allows me to more easily embed checksums into releases, avoid releases that are only tagged (not yet released), and skip known-failing releases like the recent duplicity ones.

diff --git a/prometheus/Dockerfile b/prometheus/Dockerfile
--- a/prometheus/Dockerfile
+++ b/prometheus/Dockerfile
@@ -28,8 +28,26 @@ RUN set -ex; \
 		*) echo >&2 "error: unsupported arch: $apkArch"; exit 1 ;; \
 	esac; \
 	\
-	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-${promArch}.tar.gz"; \
-# TODO sha256sums.txt
+	filename="prometheus-${PROMETHEUS_VERSION}.linux-${promArch}.tar.gz"; \
+	case "$filename" in \
+		'prometheus-2.46.0.linux-386.tar.gz') sha256='837bb7c518bd6a1478a89fe7229aa5ae4d896c2443af0a7eae0c8f1e6bdcde09' ;; \
+		'prometheus-2.46.0.linux-amd64.tar.gz') sha256='d2177ea21a6f60046f9510c828d4f8969628cfd35686780b3898917ef9c268b9' ;; \
+		'prometheus-2.46.0.linux-arm64.tar.gz') sha256='f42513c9ef63d6bed652dfc2e986b49ebec714ed784ccaac78e20e0a2a5535bc' ;; \
+		'prometheus-2.46.0.linux-armv5.tar.gz') sha256='d5f8f19df634ad5012e5ab6720a2ee181647b9212585574d50f1c1494370d3dc' ;; \
+		'prometheus-2.46.0.linux-armv6.tar.gz') sha256='e1535c1d57612efacacbb24f2e3ae39e9b99302d756a8866b5407f72c9681280' ;; \
+		'prometheus-2.46.0.linux-armv7.tar.gz') sha256='061e02d077b8f6022cf84fa9b358937c6ba6a1ba8e5914cf38c9a72aabbbe5ff' ;; \
+		'prometheus-2.46.0.linux-mips.tar.gz') sha256='c41296f69d1b794c80bcfc5162419605bae3fde7ae790510fcb737847cb9a0be' ;; \
+		'prometheus-2.46.0.linux-mips64.tar.gz') sha256='529ee6b32f13b7e98684dd1e98abe87425f80915fb3d8213660ccba6f15ed420' ;; \
+		'prometheus-2.46.0.linux-mips64le.tar.gz') sha256='8634fe0171c265463851773119c4bcc28a92275cf7450f673411adaeed122188' ;; \
+		'prometheus-2.46.0.linux-mipsle.tar.gz') sha256='4a9bba31e4f8f578ff66bd48559a91d35c3f2956c81d3e7876e7096fac9886c0' ;; \
+		'prometheus-2.46.0.linux-ppc64.tar.gz') sha256='7e750667cad37044e9d42c7187dba5566d8ac971ce3fbad27b789dca9c684ab8' ;; \
+		'prometheus-2.46.0.linux-ppc64le.tar.gz') sha256='96aeb15871ca5fcf9c12941965f047e2e563b7c757560d0c70ca68cf5f07f7dd' ;; \
+		'prometheus-2.46.0.linux-riscv64.tar.gz') sha256='3d008c0ef64dcc07fbcae41aec888108944c2aac73b9ac64d9cd1b24e6c73cf4' ;; \
+		'prometheus-2.46.0.linux-s390x.tar.gz') sha256='3a725fd91e8eb6742f8a878fa4d7222585741bc0aaedcbaf950f1c489d7793e4' ;; \
+		*) echo >&2 "error: unknown file: $filename"; exit 1 ;; \
+	esac; \
+	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/$filename"; \
+	echo "$sha256 */tmp/prom.tar.gz" | sha256sum -c -; \
 	\
 	tar \
 		--extract \
diff --git a/prometheus/Dockerfile.template b/prometheus/Dockerfile.template
--- a/prometheus/Dockerfile.template
+++ b/prometheus/Dockerfile.template
@@ -22,8 +22,15 @@ RUN set -ex; \
 		*) echo >&2 "error: unsupported arch: $apkArch"; exit 1 ;; \
 	esac; \
 	\
-	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-${promArch}.tar.gz"; \
-# TODO sha256sums.txt
+	filename="prometheus-${PROMETHEUS_VERSION}.linux-${promArch}.tar.gz"; \
+	case "$filename" in \
+{{ .sha256 | to_entries | map(select(.key | startswith("prometheus-") and contains(".linux-")) | ( -}}
+		{{ .key | @sh }}) sha256={{ .value | @sh }} ;; \
+{{ )) | add -}}
+		*) echo >&2 "error: unknown file: $filename"; exit 1 ;; \
+	esac; \
+	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/$filename"; \
+	echo "$sha256 */tmp/prom.tar.gz" | sha256sum -c -; \
 	\
 	tar \
 		--extract \
diff --git a/prometheus/alertmanager/Dockerfile b/prometheus/alertmanager/Dockerfile
--- a/prometheus/alertmanager/Dockerfile
+++ b/prometheus/alertmanager/Dockerfile
@@ -28,8 +28,25 @@ RUN set -eux; \
 		*) echo >&2 "error: unsupported arch: $apkArch"; exit 1 ;; \
 	esac; \
 	\
-	wget -O /tmp/alertmanager.tar.gz "https://github.com/prometheus/alertmanager/releases/download/v${ALERTMANAGER_VERSION}/alertmanager-${ALERTMANAGER_VERSION}.linux-${promArch}.tar.gz"; \
-# TODO sha256sums.txt
+	filename="alertmanager-${ALERTMANAGER_VERSION}.linux-${promArch}.tar.gz"; \
+	case "$filename" in \
+		'alertmanager-0.25.0.linux-386.tar.gz') sha256='daa82af3cb4d3c241f93faa011b0805ee5d357c523ac706ef83b6addd5a7e4da' ;; \
+		'alertmanager-0.25.0.linux-amd64.tar.gz') sha256='206cf787c01921574ca171220bb9b48b043c3ad6e744017030fed586eb48e04b' ;; \
+		'alertmanager-0.25.0.linux-arm64.tar.gz') sha256='20db5e4e12bcce8e2e419cc4c2bc35062ddbc14d2aacb77e4d5684c0eab7f0fe' ;; \
+		'alertmanager-0.25.0.linux-armv5.tar.gz') sha256='1a3dac97b88a2d2ef6c950965c1f84a2fb5eaaa41d5cbaa6d94b7acea522b93f' ;; \
+		'alertmanager-0.25.0.linux-armv6.tar.gz') sha256='9539413ef182e55db82e17a01cd4efdd233c78cadf9da28f8e00dcfb8b571af0' ;; \
+		'alertmanager-0.25.0.linux-armv7.tar.gz') sha256='3cfd839d4463a7679d32800258b11471498ebc49483273d588818c0432a80af1' ;; \
+		'alertmanager-0.25.0.linux-mips.tar.gz') sha256='94219bd0d8500fe4e09ce4d1c1a6b496bc2744add7d741cb988263c8cadee726' ;; \
+		'alertmanager-0.25.0.linux-mips64.tar.gz') sha256='5b288c4114bfed9e47ff809ca6350f174d74a41f2689b4da656eead719a0031e' ;; \
+		'alertmanager-0.25.0.linux-mips64le.tar.gz') sha256='985ba2d5c5d59ee542656900182d862cb5a9efdf700cee6b91aded57dad12fe4' ;; \
+		'alertmanager-0.25.0.linux-mipsle.tar.gz') sha256='f14365d9edaec4708ba58002fd7a103df7def4e61bf5c851f640dc587eb2e8b1' ;; \
+		'alertmanager-0.25.0.linux-ppc64.tar.gz') sha256='e6f90ef137a1bd48c6f85cfe19ea8576c0a159a15b0638f5fa3e5ef8733cc3c0' ;; \
+		'alertmanager-0.25.0.linux-ppc64le.tar.gz') sha256='60a64b81da8472fca3e3b413f3f812d417f78ff974180a8ecb038e5c7970934c' ;; \
+		'alertmanager-0.25.0.linux-s390x.tar.gz') sha256='26e91d3b08e82adb906f93525471c809b2c27a9f62d7482788969859e4a5d516' ;; \
+		*) echo >&2 "error: unknown file: $filename"; exit 1 ;; \
+	esac; \
+	wget -O /tmp/alertmanager.tar.gz "https://github.com/prometheus/alertmanager/releases/download/v${ALERTMANAGER_VERSION}/$filename"; \
+	echo "$sha256 */tmp/alertmanager.tar.gz" | sha256sum -c -; \
 	\
 	tar \
 		--extract \
diff --git a/prometheus/alertmanager/Dockerfile.template b/prometheus/alertmanager/Dockerfile.template
--- a/prometheus/alertmanager/Dockerfile.template
+++ b/prometheus/alertmanager/Dockerfile.template
@@ -22,8 +22,15 @@ RUN set -eux; \
 		*) echo >&2 "error: unsupported arch: $apkArch"; exit 1 ;; \
 	esac; \
 	\
-	wget -O /tmp/alertmanager.tar.gz "https://github.com/prometheus/alertmanager/releases/download/v${ALERTMANAGER_VERSION}/alertmanager-${ALERTMANAGER_VERSION}.linux-${promArch}.tar.gz"; \
-# TODO sha256sums.txt
+	filename="alertmanager-${ALERTMANAGER_VERSION}.linux-${promArch}.tar.gz"; \
+	case "$filename" in \
+{{ .sha256 | to_entries | map(select(.key | startswith("alertmanager-") and contains(".linux-")) | ( -}}
+		{{ .key | @sh }}) sha256={{ .value | @sh }} ;; \
+{{ )) | add -}}
+		*) echo >&2 "error: unknown file: $filename"; exit 1 ;; \
+	esac; \
+	wget -O /tmp/alertmanager.tar.gz "https://github.com/prometheus/alertmanager/releases/download/v${ALERTMANAGER_VERSION}/$filename"; \
+	echo "$sha256 */tmp/alertmanager.tar.gz" | sha256sum -c -; \
 	\
 	tar \
 		--extract \
diff --git a/prometheus/node-exporter/Dockerfile.template b/prometheus/node-exporter/Dockerfile.template
--- a/prometheus/node-exporter/Dockerfile.template
+++ b/prometheus/node-exporter/Dockerfile.template
@@ -19,9 +19,15 @@ RUN set -ex; \
 		s390x)    arch='s390x' ;; \
 		*)        arch='src' ;; \
 	esac; \
-# TODO sha256sums.txt
 	if [ "$arch" != 'src' ]; then \
-		url="https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.linux-${arch}.tar.gz"; \
+		filename="node_exporter-${NODE_EXPORTER_VERSION}.linux-${arch}.tar.gz"; \
+		case "$filename" in \
+{{ .sha256 | to_entries | map(select(.key | startswith("node_exporter-") and contains(".linux-")) | ( -}}
+			{{ .key | @sh }}) sha256={{ .value | @sh }} ;; \
+{{ )) | add -}}
+			*) echo >&2 "error: unknown file: $filename"; exit 1 ;; \
+		esac; \
+		url="https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/$filename"; \
 	else \
 		url="https://github.com/prometheus/node_exporter/archive/refs/tags/v${NODE_EXPORTER_VERSION}.tar.gz"; \
 	fi; \
@@ -44,6 +50,9 @@ RUN set -ex; \
 	fi; \
 	\
 	wget -O /tmp/node-exporter.tar.gz "$url"; \
+	if [ "$arch" != 'src' ]; then \
+		echo "$sha256 */tmp/node-exporter.tar.gz" | sha256sum --strict --check -; \
+	fi; \
 	\
 	tar \
 		--extract \
diff --git a/vultr-cli/Dockerfile b/vultr-cli/Dockerfile
--- a/vultr-cli/Dockerfile
+++ b/vultr-cli/Dockerfile
@@ -10,14 +10,32 @@ RUN apk add --no-cache ca-certificates
 
 # https://github.com/vultr/vultr-cli/releases
 ENV VULTR_CLI_VERSION 2.17.0
-ENV VULTR_CLI_SHA256 a9719d5761112486b13a1a7293b083e665e96c31ea0944303fa67448783bf2b6
-# TODO multiple architectures (at least "arm64" is also supported)
 
 RUN set -eux; \
-	wget -O vultr.tgz "https://github.com/vultr/vultr-cli/releases/download/v$VULTR_CLI_VERSION/vultr-cli_${VULTR_CLI_VERSION}_linux_64-bit.tar.gz"; \
-	echo "$VULTR_CLI_SHA256 *vultr.tgz" | sha256sum -c -; \
+	\
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		aarch64) vultrArch='arm64-bit' ;; \
+		armhf)   vultrArch='armv6'     ;; \
+		armv7)   vultrArch='armv7'     ;; \
+		x86_64)  vultrArch='64-bit'    ;; \
+		*) echo >&2 "error: unsupported arch: $apkArch"; exit 1 ;; \
+	esac; \
+	\
+	filename="vultr-cli_${VULTR_CLI_VERSION}_linux_${vultrArch}.tar.gz"; \
+	case "$filename" in \
+		'vultr-cli_2.17.0_linux_armv7.tar.gz') sha256='3cf74a8327444c698a66d802667997887cb16f54574455968c828a9cb07bd1bc' ;; \
+		'vultr-cli_2.17.0_linux_arm64-bit.tar.gz') sha256='47fe224b38aedeb6670a8e0c9f95a5c37c243327a8ff9fc161538b0979b58109' ;; \
+		'vultr-cli_2.17.0_linux_armv6.tar.gz') sha256='6410c537503c3d180e81c16032ad6cc110ada6f513bf0ee8a219de8a33e6c9af' ;; \
+		'vultr-cli_2.17.0_linux_64-bit.tar.gz') sha256='a9719d5761112486b13a1a7293b083e665e96c31ea0944303fa67448783bf2b6' ;; \
+		*) echo >&2 "error: unknown file: $filename"; exit 1 ;; \
+	esac; \
+	wget -O vultr.tgz "https://github.com/vultr/vultr-cli/releases/download/v$VULTR_CLI_VERSION/$filename"; \
+	echo "$sha256 *vultr.tgz" | sha256sum -c -; \
+	\
 	tar -xvf vultr.tgz -C /usr/local/bin; \
 	rm vultr.tgz; \
+	\
 	VULTR_API_KEY=fake vultr-cli version
 
 CMD ["vultr-cli", "--help"]
