Add fake browser to slack image

diff --git a/slack/Dockerfile b/slack/Dockerfile
--- a/slack/Dockerfile
+++ b/slack/Dockerfile
@@ -4,6 +4,8 @@ RUN set -eux; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
 		ca-certificates \
+# used as a fake browser so clicked URLs (and internal Slack behavior that wants to open a browser) pop up with a URL + clipboard instead of silently doing nothing
+		zenity xclip \
 	; \
 	rm -rf /var/lib/apt/lists/*
 
@@ -57,5 +59,16 @@ RUN set -eux; \
 		libgl1-mesa-dri \
 	; \
 	rm -rf /var/lib/apt/lists/*
+
+COPY browser.sh /usr/local/bin/
+ENV BROWSER /usr/local/bin/browser.sh
+RUN set -eux; \
+	for alt in \
+		gnome-www-browser \
+		www-browser \
+		x-www-browser \
+	; do \
+		update-alternatives --install "/usr/bin/$alt" "$alt" "$BROWSER" 999; \
+	done
 
 CMD ["slack"]
